import type { MemorySnapshot } from "./types";

export const FALLBACK_SNAPSHOTS: MemorySnapshot[] = [
  { id: "m-01", title: "Perfil operacional do cliente Acme Corp", category: "profile", capturedAt: "09:42", capturedAgo: "5min ago", source: "Classifier-01", summary: "Cliente enterprise, 340 funcionários, setor tech B2B. Ciclo de compra longo (90d avg). Decision makers: CTO e VP Engineering. Último contato: proposta de expansão de licenças.", context: "Capturado durante classificação do batch #4821. Consolidação de 14 interações anteriores.", tags: ["enterprise", "b2b", "expansion"], relevance: "high" },
  { id: "m-02", title: "Padrão de falha recorrente no Data Pipeline", category: "incident", capturedAt: "09:38", capturedAgo: "9min ago", source: "Health Monitor", summary: "Latência P95 ultrapassa 150ms quando volume de ingestão excede 50k eventos/min. Ocorrência: 3x nos últimos 7 dias. Causa raiz provável: buffer de memória do worker saturado.", context: "Correlação identificada automaticamente entre picos de volume e degradação de performance.", tags: ["pipeline", "latency", "recurring"], relevance: "high" },
  { id: "m-03", title: "Decisão: modelo GPT-4o para classificação de leads", category: "decision", capturedAt: "09:15", capturedAgo: "32min ago", source: "Mission Control", summary: "Após testes A/B com GPT-4o-mini, decidido manter GPT-4o para classificação por accuracy superior (97.3% vs 91.2%). Custo 3x maior compensado por redução de retrabalho manual.", context: "Decisão tomada pelo operador após análise de 3 batches comparativos.", tags: ["model-selection", "accuracy", "cost"], relevance: "medium" },
  { id: "m-04", title: "Contexto de negociação — Deal #7234", category: "context", capturedAt: "08:55", capturedAgo: "52min ago", source: "Summarizer-01", summary: "Prospect solicitou desconto de 20% para contrato anual. Histórico mostra que deals similares fecharam com 12-15% de desconto. Competitor ativo: Salesforce. Deadline do prospect: fim do trimestre.", context: "Extraído de thread de email com 8 mensagens. Sumarização automática.", tags: ["deal", "negotiation", "discount"], relevance: "high" },
  { id: "m-05", title: "Aprendizado: retry policy ideal para APIs externas", category: "learning", capturedAt: "08:30", capturedAgo: "1h17 ago", source: "Enricher-01", summary: "Clearbit responde melhor com exponential backoff iniciando em 2s (vs 1s anterior). Rate limit de 100 req/min. LinkedIn API mais estável com batch de 10 requests vs individual. Economia de 40% em tokens.", context: "Aprendizado consolidado após 14 dias de operação contínua com ajustes incrementais.", tags: ["api", "retry", "optimization"], relevance: "medium" },
  { id: "m-06", title: "Configuração validada: thresholds de alerta", category: "config", capturedAt: "08:00", capturedAgo: "1h47 ago", source: "Monitor-01", summary: "Thresholds atuais: CPU > 80% (warning), > 95% (critical). RAM > 75% (warning), > 90% (critical). Latência P95 > 100ms (warning), > 200ms (critical). Validados contra últimos 30 dias de operação.", context: "Snapshot de configuração após health check matinal. Sem ajustes necessários.", tags: ["thresholds", "alerts", "config"], relevance: "low" },
  { id: "m-07", title: "Perfil comportamental — Segmento SMB", category: "profile", capturedAt: "07:30", capturedAgo: "2h17 ago", source: "Analyzer-01", summary: "Leads SMB convertem 2.3x mais rápido que enterprise mas com ticket médio 5x menor. Canal preferido: email (62%), seguido de chat (24%). Melhor horário de contato: 10-11h e 14-15h.", context: "Análise de padrões sobre 2.4k leads processados no último trimestre.", tags: ["smb", "conversion", "patterns"], relevance: "medium" },
  { id: "m-08", title: "Incidente resolvido: deploy v2.14.2 rollback", category: "incident", capturedAt: "07:00", capturedAgo: "2h47 ago", source: "Core Engine", summary: "Deploy v2.14.2 causou regressão no endpoint /api/classify. Rollback automático acionado em 2min. Root cause: dependência incompatível com Node 20.x. Fix aplicado no v2.14.3.", context: "Post-mortem automático gerado. Tempo de impacto: 4min. Zero perda de dados.", tags: ["deploy", "rollback", "postmortem"], relevance: "medium" },
];
