import type { CronJob } from "./types";

export const FALLBACK_CRON_JOBS: CronJob[] = [
  { id: "j-01", name: "Health Check Global", schedule: "*/5 * * * *", scheduleHuman: "Every 5 min", enabled: true, status: "healthy", lastRun: "09:45", lastRunAgo: "2min ago", lastDuration: "4s", lastResult: "success", nextRun: "09:50", nextRunIn: "in 3min", consecutiveSuccess: 847, consecutiveFails: 0 },
  { id: "j-02", name: "Backup Database", schedule: "0 */6 * * *", scheduleHuman: "Every 6h", enabled: true, status: "healthy", lastRun: "06:00", lastRunAgo: "3h47 ago", lastDuration: "2m34s", lastResult: "success", nextRun: "12:00", nextRunIn: "in 2h13", consecutiveSuccess: 120, consecutiveFails: 0 },
  { id: "j-03", name: "Sync CRM Incremental", schedule: "*/15 * * * *", scheduleHuman: "Every 15 min", enabled: true, status: "healthy", lastRun: "09:30", lastRunAgo: "17min ago", lastDuration: "48s", lastResult: "success", nextRun: "09:45", nextRunIn: "in 0min", consecutiveSuccess: 312, consecutiveFails: 0 },
  { id: "j-04", name: "Limpar Temp Files", schedule: "0 3 * * *", scheduleHuman: "Daily 03:00", enabled: true, status: "healthy", lastRun: "03:00", lastRunAgo: "6h47 ago", lastDuration: "12s", lastResult: "success", nextRun: "03:00 +1d", nextRunIn: "in 17h13", consecutiveSuccess: 47, consecutiveFails: 0 },
  { id: "j-05", name: "Refresh Materialized Views", schedule: "0 */2 * * *", scheduleHuman: "Every 2h", enabled: true, status: "healthy", lastRun: "08:00", lastRunAgo: "1h47 ago", lastDuration: "1m18s", lastResult: "success", nextRun: "10:00", nextRunIn: "in 13min", consecutiveSuccess: 560, consecutiveFails: 0 },
  { id: "j-06", name: "Export Métricas Prometheus", schedule: "*/1 * * * *", scheduleHuman: "Every 1 min", enabled: true, status: "warning", lastRun: "09:46", lastRunAgo: "1min ago", lastDuration: "8s", lastResult: "success", nextRun: "09:47", nextRunIn: "in 0min", consecutiveSuccess: 14, consecutiveFails: 0, error: "Latência acima do normal nas últimas 3 execuções (avg 8s vs 2s normal)" },
  { id: "j-07", name: "Reprocessar Eventos Falhos", schedule: "*/30 * * * *", scheduleHuman: "Every 30 min", enabled: true, status: "failed", lastRun: "09:30", lastRunAgo: "17min ago", lastDuration: "2s", lastResult: "failure", nextRun: "10:00", nextRunIn: "in 13min", consecutiveSuccess: 0, consecutiveFails: 3, error: "ConnectionRefusedError: Unable to connect to event-processor:8081 — service may be down" },
  { id: "j-08", name: "Rotate Logs", schedule: "0 2 * * *", scheduleHuman: "Daily 02:00", enabled: true, status: "healthy", lastRun: "02:00", lastRunAgo: "7h47 ago", lastDuration: "6s", lastResult: "success", nextRun: "02:00 +1d", nextRunIn: "in 16h13", consecutiveSuccess: 47, consecutiveFails: 0 },
  { id: "j-09", name: "Warm ML Model Cache", schedule: "0 7 * * *", scheduleHuman: "Daily 07:00", enabled: true, status: "healthy", lastRun: "07:00", lastRunAgo: "2h47 ago", lastDuration: "3m42s", lastResult: "success", nextRun: "07:00 +1d", nextRunIn: "in 21h13", consecutiveSuccess: 12, consecutiveFails: 0 },
  { id: "j-10", name: "Report Semanal (Deprecated)", schedule: "0 8 * * 1", scheduleHuman: "Mon 08:00", enabled: false, status: "disabled", lastRun: "—", lastRunAgo: "—", lastDuration: "—", lastResult: "—", nextRun: "—", nextRunIn: "—", consecutiveSuccess: 0, consecutiveFails: 0 },
  { id: "j-11", name: "Purge Expired Tokens", schedule: "0 4 * * *", scheduleHuman: "Daily 04:00", enabled: false, status: "disabled", lastRun: "04:00 (3d ago)", lastRunAgo: "3d ago", lastDuration: "1s", lastResult: "success", nextRun: "—", nextRunIn: "—", consecutiveSuccess: 0, consecutiveFails: 0 },
];
