import type { Alert } from "./types";

export const FALLBACK_ALERTS: Alert[] = [
  { id: "a-01", severity: "critical", title: "Validator-01 offline — conexão com API externa perdida", description: "Agente não responde há 14min. 3 retries falharam com timeout. Tarefas de validação suspensas.", action: "Verificar conectividade com api.external-service.com:443 e reiniciar agente", source: "Validator-01", triggeredAt: "09:33", triggeredAgo: "14min ago", acknowledged: false, occurrences: 1 },
  { id: "a-02", severity: "critical", title: "Cron job 'Reprocessar Eventos Falhos' com 3 falhas consecutivas", description: "ConnectionRefusedError: event-processor:8081. Serviço de processamento pode estar down.", action: "Verificar status do event-processor e logs do container", source: "Cron Scheduler", triggeredAt: "09:30", triggeredAgo: "17min ago", acknowledged: true, occurrences: 3 },
  { id: "a-03", severity: "warning", title: "Data Pipeline com latência P95 elevada", description: "P95 em 187ms (threshold: 100ms). Volume de ingestão 3x acima do normal. Causa: pico de dados.", action: "Monitorar. Considerar scale-up do worker pool se persistir por +30min", source: "Data Pipeline", triggeredAt: "09:28", triggeredAgo: "19min ago", acknowledged: true, occurrences: 1 },
  { id: "a-04", severity: "warning", title: "Sync-01 com carga em 91%", description: "Sync CRM com 2.1k registros simultâneos. Próximo do limite operacional.", action: "Aguardar conclusão da sessão atual. Reduzir batch size se carga não baixar", source: "Sync-01", triggeredAt: "09:34", triggeredAgo: "13min ago", acknowledged: false, occurrences: 1 },
  { id: "a-05", severity: "warning", title: "Rate limit atingido na API Clearbit", description: "HTTP 429 retornado. Backoff exponencial ativado automaticamente.", action: "Nenhuma ação necessária. Retry automático em 60s", source: "Enricher-01", triggeredAt: "09:15", triggeredAgo: "32min ago", acknowledged: true, occurrences: 2 },
  { id: "a-06", severity: "warning", title: "Process count acima da média", description: "247 processos ativos (média: 210). Sem impacto de performance detectado ainda.", action: "Monitorar. Investigar se persistir acima de 260", source: "System Monitor", triggeredAt: "09:10", triggeredAgo: "37min ago", acknowledged: false, occurrences: 1 },
  { id: "a-07", severity: "warning", title: "Export métricas com latência elevada", description: "Cron de export Prometheus levando 8s (normal: 2s) nas últimas 3 execuções.", action: "Verificar volume de métricas e estado do Prometheus endpoint", source: "Cron Scheduler", triggeredAt: "09:46", triggeredAgo: "1min ago", acknowledged: false, occurrences: 3 },
  { id: "a-08", severity: "info", title: "Deploy v2.14.3 aguardando aprovação", description: "Build validado em staging. Todos os testes passaram. Aguardando approval manual.", action: "Aprovar deploy para produção quando conveniente", source: "Release Pipeline", triggeredAt: "08:30", triggeredAgo: "1h17 ago", acknowledged: true, occurrences: 1 },
  { id: "a-09", severity: "info", title: "Classificação Batch #4821 em progresso — 67%", description: "8.4k leads em processamento. ETA: 12min. Sem anomalias.", action: "Nenhuma ação necessária", source: "Classifier-01", triggeredAt: "09:28", triggeredAgo: "19min ago", acknowledged: true, occurrences: 1 },
  { id: "a-10", severity: "info", title: "Session s-4816 pausada por operador", description: "Reprocessamento de eventos pausado manualmente. 480 eventos na fila.", action: "Retomar quando pronto", source: "Analyzer-01", triggeredAt: "08:45", triggeredAgo: "1h02 ago", acknowledged: true, occurrences: 1 },
  { id: "a-11", severity: "resolved", title: "Rollback v2.14.2 concluído com sucesso", description: "Pipeline restaurado. Performance normalizada em 4min. Zero perda de dados.", action: "Resolvido automaticamente", source: "Core Engine", triggeredAt: "09:42", triggeredAgo: "5min ago", resolvedAt: "09:42", acknowledged: true, occurrences: 1 },
  { id: "a-12", severity: "resolved", title: "Health check matinal concluído", description: "11/12 serviços nominais. Data Pipeline flagged para monitoramento contínuo.", action: "Resolvido", source: "Health Monitor", triggeredAt: "08:00", triggeredAgo: "1h47 ago", resolvedAt: "08:02", acknowledged: true, occurrences: 1 },
];
